#!/usr/bin/env python3

import os
import sys

# Display a logo
logo = """
    _         _   _  __            _   ____              
   / \   _ __| |_(_)/ _| __ _  ___| |_/ ___| _ __  _   _ 
  / _ \ | '__| __| | |_ / _` |/ __| __\___ \| '_ \| | | |
 / ___ \| |  | |_| |  _| (_| | (__| |_ ___) | |_) | |_| |
/_/   \_\_|   \__|_|_|  \__,_|\___|\__|____/| .__/ \__, |
                                            |_|    |___/ 
"""
print('\n\n\n' + logo + '\n')


# Setup directory structure
if not os.path.exists('Results'):
    os.mkdir('Results')
if not os.path.exists('Data'):
    os.mkdir('Data')
os.chdir('Code')

# Prompt user for login
hep_username = input("Enter your UW-Madison HEP Username: ")

# Get a Kerberos ticket
os.system('kinit {}@HEP.WISC.EDU'.format(hep_username))

# Check that username is accurate
test_command = "ssh {}@login04.hep.wisc.edu 'touch /afs/hep.wisc.edu/bechtol-group/ArtifactSpy/test.txt'".format(hep_username)
err_code = os.system(test_command)

if err_code != 0:
    print("\nError: Unable to login to UW-Madison HEP Computers.\n" +
          "\t - Check that your username was entered correctly\n" +
          "\t - Check that you have properly kerber-ized your computer\n\n")
    sys.exit()


os.system('python manager.py --username {}'.format(hep_username))
